/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._ad_u03;

import java.awt.Component;
import java.awt.Container;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.exception.ConstraintViolationException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.hibernate.Query;

/**
 *
 * @author anaranjo
 */
public class EducacionInfantil_JFrame extends javax.swing.JFrame {

    static String etiquetaEducadorBorrado;
    static String etiquetaGuarderiaBorrada;
    static String listadoGuarderias;
    static String etiquetaListadoGuarderias;

    /**
     * Creates new form EducacionInfantil_JFrame
     */
    public EducacionInfantil_JFrame() {
        initComponents();
        // Ventana centrada en la pantalla
        this.setLocationRelativeTo(null);
        // Título de la ventana
        this.setTitle("Gestión de Centros de Educación Infantil - Autor: Antonio Naranjo Castillo - DAM curso 25/26");

        refrescarComboBoxEducadoresUnicos();
        refrescarComboBoxGuarderiasUnicas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAgregarGuarderia = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cdagTextField = new javax.swing.JTextField();
        nmgTextField = new javax.swing.JTextField();
        cpgTextField = new javax.swing.JTextField();
        ppgTextField = new javax.swing.JTextField();
        agregarGuarderiaButton = new javax.swing.JButton();
        limpiarAgregarGuarderiaButton = new javax.swing.JButton();
        jPanelAgregarEducador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dniaTextField = new javax.swing.JTextField();
        nmeTextField = new javax.swing.JTextField();
        apeTextField = new javax.swing.JTextField();
        cgeTextField = new javax.swing.JTextField();
        fneTextField = new javax.swing.JTextField();
        faeTextField = new javax.swing.JTextField();
        sleTextField = new javax.swing.JTextField();
        limpiarAgregarEducadorButton = new javax.swing.JButton();
        agregarEducadorButton = new javax.swing.JButton();
        jPanelEliminarGuarderia = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        eliminarGuarderiaButton = new javax.swing.JButton();
        jComboBoxGuarderias = new javax.swing.JComboBox<>();
        jLabelBorrarGuarderia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelEliminarEducador = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        eliminarEducadorButton = new javax.swing.JButton();
        jComboBoxEducadores = new javax.swing.JComboBox<>();
        jLabelBorrarEducador = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        listarGuarderiaButton = new javax.swing.JButton();
        jLabelListadoGuarderias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAgregarGuarderia.setFocusCycleRoot(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Guarderías");

        jLabel3.setText("Código");

        jLabel4.setText("Nombre");

        jLabel5.setText("Capacidad");

        jLabel6.setText("Presupuesto");

        cdagTextField.setToolTipText("Tipo de dato varchar(5)");

        nmgTextField.setToolTipText("Tipo de dato varchar(40)");

        cpgTextField.setToolTipText("Tipo de dato int");

        ppgTextField.setToolTipText("Tipo de dato float");

        agregarGuarderiaButton.setText("Añadir");
        agregarGuarderiaButton.setToolTipText("Añadir una nueva guardería");
        agregarGuarderiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarGuarderiaButtonActionPerformed(evt);
            }
        });

        limpiarAgregarGuarderiaButton.setText("Limpiar");
        limpiarAgregarGuarderiaButton.setToolTipText("Limpiar datos de los campos de texto");
        limpiarAgregarGuarderiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAgregarGuarderiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarGuarderiaLayout = new javax.swing.GroupLayout(jPanelAgregarGuarderia);
        jPanelAgregarGuarderia.setLayout(jPanelAgregarGuarderiaLayout);
        jPanelAgregarGuarderiaLayout.setHorizontalGroup(
            jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarGuarderiaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAgregarGuarderiaLayout.createSequentialGroup()
                        .addComponent(limpiarAgregarGuarderiaButton)
                        .addGap(18, 18, 18)
                        .addComponent(agregarGuarderiaButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelAgregarGuarderiaLayout.setVerticalGroup(
            jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarGuarderiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cdagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nmgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cpgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ppgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarAgregarGuarderiaButton)
                    .addComponent(agregarGuarderiaButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelAgregarEducador.setFocusCycleRoot(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Educadores");

        jLabel8.setText("DNI");

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellidos");

        jLabel11.setText("Fecha Nacimiento");

        jLabel12.setText("Fecha Alta");

        jLabel13.setText("Salario");

        jLabel14.setText("Codigo Guarderia");

        dniaTextField.setToolTipText("Tipo de dato varchar(9) ");

        nmeTextField.setToolTipText("Tipo de dato varchar(30)");

        apeTextField.setToolTipText("Tipo de dato varchar(70)");

        cgeTextField.setToolTipText("Tipo de dato varchar(5)");

        fneTextField.setToolTipText("Tipo de dato date");

        faeTextField.setToolTipText("Tipo de dato date");

        sleTextField.setToolTipText("Tipo de dato float");

        limpiarAgregarEducadorButton.setText("Limpiar");
        limpiarAgregarEducadorButton.setToolTipText("Limpiar datos de los campos de texto");
        limpiarAgregarEducadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAgregarEducadorButtonActionPerformed(evt);
            }
        });

        agregarEducadorButton.setText("Añadir");
        agregarEducadorButton.setToolTipText("Añadir un nuevo educador");
        agregarEducadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEducadorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarEducadorLayout = new javax.swing.GroupLayout(jPanelAgregarEducador);
        jPanelAgregarEducador.setLayout(jPanelAgregarEducadorLayout);
        jPanelAgregarEducadorLayout.setHorizontalGroup(
            jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dniaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nmeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarEducadorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addComponent(apeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(cgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarEducadorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(limpiarAgregarEducadorButton)
                        .addGap(18, 18, 18)
                        .addComponent(agregarEducadorButton)
                        .addGap(61, 61, 61)))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fneTextField)
                    .addComponent(faeTextField)
                    .addComponent(sleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanelAgregarEducadorLayout.setVerticalGroup(
            jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarEducadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dniaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(fneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nmeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(faeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(sleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelAgregarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarAgregarEducadorButton)
                    .addComponent(agregarEducadorButton))
                .addGap(35, 35, 35))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Guarderías");

        jLabel17.setText("Código");

        eliminarGuarderiaButton.setText("Borrar");
        eliminarGuarderiaButton.setToolTipText("Borrar una guardería");
        eliminarGuarderiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarGuarderiaButtonActionPerformed(evt);
            }
        });

        jComboBoxGuarderias.setToolTipText("");

        jLabelBorrarGuarderia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBorrarGuarderia.setText("Nombre de la guardería a eliminar");
        jLabelBorrarGuarderia.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelEliminarGuarderiaLayout = new javax.swing.GroupLayout(jPanelEliminarGuarderia);
        jPanelEliminarGuarderia.setLayout(jPanelEliminarGuarderiaLayout);
        jPanelEliminarGuarderiaLayout.setHorizontalGroup(
            jPanelEliminarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarGuarderiaLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEliminarGuarderiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEliminarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarGuarderiaLayout.createSequentialGroup()
                        .addComponent(jLabelBorrarGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEliminarGuarderiaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxGuarderias, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(eliminarGuarderiaButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelEliminarGuarderiaLayout.setVerticalGroup(
            jPanelEliminarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarGuarderiaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxGuarderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarGuarderiaButton))
                .addGap(18, 18, 18)
                .addComponent(jLabelBorrarGuarderia)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("1) Añadir Objetos");
        jLabel1.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Educadores");

        jLabel19.setText("DNI");

        eliminarEducadorButton.setText("Borrar");
        eliminarEducadorButton.setToolTipText("Borrar un educador");
        eliminarEducadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEducadorButtonActionPerformed(evt);
            }
        });

        jComboBoxEducadores.setToolTipText("");

        jLabelBorrarEducador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBorrarEducador.setText("Nombre del educador a eliminar");
        jLabelBorrarEducador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelEliminarEducadorLayout = new javax.swing.GroupLayout(jPanelEliminarEducador);
        jPanelEliminarEducador.setLayout(jPanelEliminarEducadorLayout);
        jPanelEliminarEducadorLayout.setHorizontalGroup(
            jPanelEliminarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarEducadorLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEliminarEducadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEliminarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBorrarEducador, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEliminarEducadorLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxEducadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarEducadorButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelEliminarEducadorLayout.setVerticalGroup(
            jPanelEliminarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarEducadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarEducadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxEducadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarEducadorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBorrarEducador)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("2) Eliminar Objetos");
        jLabel20.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("3) Listar Guarderías");
        jLabel15.setToolTipText("");

        listarGuarderiaButton.setText("Listar");
        listarGuarderiaButton.setToolTipText("Listar todas las guarderías");
        listarGuarderiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarGuarderiaButtonActionPerformed(evt);
            }
        });

        jLabelListadoGuarderias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelListadoGuarderias.setText("Listado de guarderías");
        jLabelListadoGuarderias.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(81, 81, 81)
                        .addComponent(listarGuarderiaButton))
                    .addComponent(jLabelListadoGuarderias, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(listarGuarderiaButton))
                .addGap(18, 18, 18)
                .addComponent(jLabelListadoGuarderias, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelAgregarGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelEliminarGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelAgregarEducador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelEliminarEducador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel20)
                    .addContainerGap(984, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAgregarEducador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAgregarGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEliminarGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEliminarEducador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(327, 327, 327)
                    .addComponent(jLabel20)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEducadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEducadorButtonActionPerformed
        // TODO add your handling code here:

        // Declaración de campos de la tabla Guarderia
        // Iniciación de variables vinculadas a los campos de texto de la interfaz
        String dni = dniaTextField.getText();
        String nombre = nmeTextField.getText();
        String apellidos = apeTextField.getText();
        String codigoGuarde = cgeTextField.getText();
        Guarderia guarde = new Guarderia(codigoGuarde);
        String fechaNac = faeTextField.getText();
        String fechaAlt = faeTextField.getText();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaNacimiento = null;
        Date fechaAlta = null;

        try {
            fechaNacimiento = formato.parse(fechaNac);
            fechaAlta = formato.parse(fechaAlt);
        } catch (ParseException ex) {
            Logger.getLogger(EducacionInfantil_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Float salario = Float.parseFloat(sleTextField.getText());

        // Se inicia una sesión
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            // Se llama el método agregarGuarderia() para añadir una guardería a la base de datos
            agregarEducador(session, dni, nombre, apellidos, fechaNacimiento, fechaAlta, salario, guarde);
            // Se cierra la sesión
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
        refrescarComboBoxEducadoresUnicos();
        jComboBoxEducadores.setSelectedIndex(0);
    }//GEN-LAST:event_agregarEducadorButtonActionPerformed

    private void eliminarGuarderiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarGuarderiaButtonActionPerformed
        // TODO add your handling code here:

        // Declaración de campos de la tabla Guarderia
        // Iniciación de variables vinculadas a los campos de texto de la interfaz
        int item;
        String codigoGuarderia;
        item = jComboBoxGuarderias.getSelectedIndex();
        codigoGuarderia = jComboBoxGuarderias.getItemAt(item).toUpperCase();

        // Se inicia una sesión
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            // Se realiza una consulta para comprobar que no existan educadores asociados a la guardería que se pretende eliminar
            // Si la consulta está vacía entonces se procede a borrar la guardería, pero si no se muestra un mensaje al usuario de impedimento
            if (consultarEducador(session, codigoGuarderia).isEmpty()) {
                // Se llama el método agregarGuarderia() para añadir una guardería a la base de datos
                borrarGuarderia(session, codigoGuarderia);
                jLabelBorrarGuarderia.setText(etiquetaGuarderiaBorrada);
            } else {
                JOptionPane.showMessageDialog(null, "Existen educadores asignados a la guardería: " + codigoGuarderia + ". La guardería no se puede borrar.");
            }

            // Se cierra la sesión
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
        refrescarComboBoxGuarderiasUnicas();
        jComboBoxGuarderias.setSelectedIndex(0);
    }//GEN-LAST:event_eliminarGuarderiaButtonActionPerformed

    private void limpiarAgregarGuarderiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAgregarGuarderiaButtonActionPerformed
        // TODO add your handling code here:
        limpiarCampos(jPanelAgregarGuarderia);
    }//GEN-LAST:event_limpiarAgregarGuarderiaButtonActionPerformed

    private void agregarGuarderiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarGuarderiaButtonActionPerformed
        // TODO add your handling code here:

        // Declaración de campos de la tabla Guarderia
        // Iniciación de variables vinculadas a los campos de texto de la interfaz
        String codigo = cdagTextField.getText();
        String nombre = nmgTextField.getText();
        Integer capacidad = Integer.parseInt(cpgTextField.getText());
        Float presupuesto = Float.parseFloat(ppgTextField.getText());

        // Se inicia una sesión
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            // Se llama el método agregarGuarderia() para añadir una guardería a la base de datos
            agregarGuarderia(session, codigo, nombre, capacidad, presupuesto);

            // Se cierra la sesión
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
        refrescarComboBoxGuarderiasUnicas();
        jComboBoxGuarderias.setSelectedIndex(0);
    }//GEN-LAST:event_agregarGuarderiaButtonActionPerformed

    private void limpiarAgregarEducadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAgregarEducadorButtonActionPerformed
        // TODO add your handling code here:
        limpiarCampos(jPanelAgregarEducador);
    }//GEN-LAST:event_limpiarAgregarEducadorButtonActionPerformed

    private void eliminarEducadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEducadorButtonActionPerformed
        // TODO add your handling code here:
        // Declaración de campos de la tabla Guarderia
        // Iniciación de variables vinculadas a los campos de texto de la interfaz
        int item;
        String dniEducador;
        item = jComboBoxEducadores.getSelectedIndex();
        dniEducador = jComboBoxEducadores.getItemAt(item).toUpperCase();
        // Se inicia una sesión
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            // Se llama el método agregarGuarderia() para añadir una guardería a la base de datos
            borrarEducador(session, dniEducador);

            jLabelBorrarEducador.setText(etiquetaEducadorBorrado);

            // Se cierra la sesión
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
        refrescarComboBoxEducadoresUnicos();
        jComboBoxEducadores.setSelectedIndex(0);
    }//GEN-LAST:event_eliminarEducadorButtonActionPerformed

    private void listarGuarderiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarGuarderiaButtonActionPerformed
        // TODO add your handling code here:

        // Se inicia una sesión
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            // Se llama el método agregarGuarderia() para añadir una guardería a la base de datos
            consultarGuarderia(session);
            jLabelListadoGuarderias.setText(etiquetaListadoGuarderias);
            System.out.print(listadoGuarderias);
             JOptionPane.showMessageDialog(null, listadoGuarderias);
            // Se cierra la sesión
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_listarGuarderiaButtonActionPerformed

    static void agregarGuarderia(Session ss, String codigo, String nombre, Integer capacidad, Float presupuesto) {

        // Se declara/instancia un objeto tipo Transaction
        Transaction tst = ss.beginTransaction();

        try {

            Guarderia guarde = new Guarderia(codigo);
            guarde.setNombre(nombre);
            guarde.setCapacidad(capacidad);
            guarde.setPresupuesto(presupuesto);
            ss.save(guarde);

            tst.commit();

        } catch (ConstraintViolationException e) {

            if (tst != null) {
                // Hacer rollback si hay un error
                tst.rollback();
            }
            System.out.println(e.getMessage());

        } catch (Exception e) {

            if (tst != null) {
                // Hacer rollback para cualquier otro error
                tst.rollback();
            }
            System.out.println("No se ha podido guardar el objeto guardería" + e.getMessage());
        }
    }

    static void agregarEducador(Session ss, String dni, String nombre, String apellidos, Date fechaNacimiento, Date fechaAlta, Float salario, Guarderia codigoGuarderia) {

        // Se declara/instancia un objeto tipo Transaction
        Transaction tst = ss.beginTransaction();

        try {

            EducadorInfantil educador = new EducadorInfantil(dni);
            educador.setNombre(nombre);
            educador.setApellidos(apellidos);
            educador.setFechaNacimiento(fechaNacimiento);
            educador.setFechaAlta(fechaAlta);
            educador.setSalario(salario);
            educador.setCodigoGuarderia(codigoGuarderia);
            ss.save(educador);

            tst.commit();

        } catch (ConstraintViolationException e) {

            if (tst != null) {
                // Hacer rollback si hay un error
                tst.rollback();
            }
            System.out.println(e.getMessage());

        } catch (Exception e) {

            if (tst != null) {
                // Hacer rollback para cualquier otro error
                tst.rollback();
            }
            System.out.println("No se ha podido guardar el objeto educador" + e.getMessage());
        }
    }

    static void borrarGuarderia(Session ss, String codigo) {

        Transaction tst = ss.beginTransaction();

        try {

            Guarderia guarde = ss.get(Guarderia.class, codigo);

            if (guarde == null) {
                System.out.println("No se encontró la guardería con código: " + codigo);
            } else {

                // Se realiza una consulta
                // Borrar guardería
                ss.delete(guarde);
                System.out.println("Se borró la guardería con código: " + codigo);
                etiquetaGuarderiaBorrada = "La guardería " + guarde.getNombre() + " ha sido eliminada con éxito.";
            }

            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {

            if (tst != null) {
                // Hacer rollback en caso de error
                tst.rollback();
            }
            System.out.println(e.getMessage());
        }
    }

    static List<EducadorInfantil> consultarEducador(Session ss, String codigoGuarde) {

        Transaction tst = ss.beginTransaction();
        List<EducadorInfantil> educadores = new ArrayList<>();

        try {
            Query<EducadorInfantil> query = ss.createQuery("from EducadorInfantil e where codigoGuarderia.codigo=:cod", EducadorInfantil.class);
            query.setParameter("cod", codigoGuarde);
            educadores = query.list();

            for (EducadorInfantil educador : educadores) {
                System.out.println("EducadorInfantil: " + educador.getNombre() + " --DNI: " + educador.getDni());
            }

            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return educadores;
    }

    static void borrarEducador(Session ss, String codigo) {

        Transaction tst = ss.beginTransaction();

        try {

            EducadorInfantil educador = ss.get(EducadorInfantil.class, codigo);

            if (educador == null) {
                System.out.println("No se encontró el educador infantil con código: " + codigo);
            } else {

                // Se realiza una consulta
                // Borrar guardería
                ss.delete(educador);
                System.out.println("Se borró el educador infantil con código: " + codigo);
                etiquetaEducadorBorrado = "El educador " + educador.getNombre() + " " + educador.getApellidos() + " ha sido eliminado con éxito.";

            }

            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {

            if (tst != null) {
                // Hacer rollback en caso de error
                tst.rollback();
            }
            System.out.println(e.getMessage());
        }

    }

    static List<Guarderia> consultarGuarderia(Session ss) {

        Transaction tst = ss.beginTransaction();
        List<Guarderia> guarderias = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        StringBuilder sbHTML = new StringBuilder("<html>");
        String texto;
        
        try {
            Query<Guarderia> query = ss.createQuery("from Guarderia g", Guarderia.class);
            guarderias = query.list();

            for (Guarderia guarde : guarderias) {
                texto="Guardería: " + guarde.getNombre() + " --Código: " + guarde.getCodigo() + " --Capacidad: " + guarde.getCapacidad() + " --Presupuesto: " + guarde.getPresupuesto();
                System.out.println(texto);
                sb.append(texto).append("\n");
                sbHTML.append(texto).append("<br>");
            }
            sbHTML.append("</html>");
                listadoGuarderias=sb.toString();
                etiquetaListadoGuarderias=sbHTML.toString();
            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return guarderias;
    }

    static List<String> dniValoresUnicosEducadores(Session ss) {

        Transaction tst = ss.beginTransaction();
        List<String> dniUnicos = new ArrayList<>();
        try {
            Query<String> query = ss.createQuery("select distinct e.dni from EducadorInfantil e", String.class);
            dniUnicos = query.list();

            for (String dni : dniUnicos) {
                System.out.println("Educador único con DNI: " + dni);
            }

            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return dniUnicos;
    }

    static List<String> codigoValoresUnicosGuarderias(Session ss) {

        Transaction tst = ss.beginTransaction();
        List<String> codigosUnicos = new ArrayList<>();
        try {
            Query<String> query = ss.createQuery("select distinct g.codigo from Guarderia g", String.class);
            codigosUnicos = query.list();

            for (String codigo : codigosUnicos) {
                System.out.println("Guardería única con codigo: " + codigo);
            }

            // Se confirma la transacción
            tst.commit();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return codigosUnicos;
    }

    private void refrescarComboBoxEducadoresUnicos() {

         jComboBoxEducadores.removeAllItems();
// Se alimenta el combobox de educadores (valores únicos)
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            for (String dni : dniValoresUnicosEducadores(session)) {
                jComboBoxEducadores.addItem(dni);
            }
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
    }

    private void refrescarComboBoxGuarderiasUnicas() {

        jComboBoxGuarderias.removeAllItems();
// Se alimenta el combobox de educadores (valores únicos)
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            for (String codigo : codigoValoresUnicosGuarderias(session)) {
                jComboBoxGuarderias.addItem(codigo);
            }
            session.close();

        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Limpia todos los campos de entrada dentro de un contenedor dado.
     *
     * @param contenedor El contenedor a limpiar
     */
    public void limpiarCampos(Container contenedor) {

        // Se crea una lista de componentes que contiene un contenedor
        Component[] componentes = contenedor.getComponents();

        // Por cada componente del contenedor, dependiendo de qué tipo de componente sea lo limpia o desmarca
        for (Component componente : componentes) {

            if (componente instanceof JTextField) {
                ((JTextField) componente).setText("");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EducacionInfantil_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EducacionInfantil_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EducacionInfantil_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EducacionInfantil_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EducacionInfantil_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEducadorButton;
    private javax.swing.JButton agregarGuarderiaButton;
    private javax.swing.JTextField apeTextField;
    private javax.swing.JTextField cdagTextField;
    private javax.swing.JTextField cgeTextField;
    private javax.swing.JTextField cpgTextField;
    private javax.swing.JTextField dniaTextField;
    private javax.swing.JButton eliminarEducadorButton;
    private javax.swing.JButton eliminarGuarderiaButton;
    private javax.swing.JTextField faeTextField;
    private javax.swing.JTextField fneTextField;
    private javax.swing.JComboBox<String> jComboBoxEducadores;
    private javax.swing.JComboBox<String> jComboBoxGuarderias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBorrarEducador;
    private javax.swing.JLabel jLabelBorrarGuarderia;
    private javax.swing.JLabel jLabelListadoGuarderias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAgregarEducador;
    private javax.swing.JPanel jPanelAgregarGuarderia;
    private javax.swing.JPanel jPanelEliminarEducador;
    private javax.swing.JPanel jPanelEliminarGuarderia;
    private javax.swing.JButton limpiarAgregarEducadorButton;
    private javax.swing.JButton limpiarAgregarGuarderiaButton;
    private javax.swing.JButton listarGuarderiaButton;
    private javax.swing.JTextField nmeTextField;
    private javax.swing.JTextField nmgTextField;
    private javax.swing.JTextField ppgTextField;
    private javax.swing.JTextField sleTextField;
    // End of variables declaration//GEN-END:variables
}
